### ISSUE TITLE
Fetching motifs returns wrong species

### ISSUE THREAD

**Issue by karolyp** [asntech/pyjaspar#1]
I selected a TF and wanted to query its data as follows:
```python
from pyjaspar import jaspardb
jdb_obj = jaspardb()
motifs = jdb_obj.fetch_motifs_by_name('FOS')
list(map(lambda m: (m.matrix_id, m.species), motifs))
```
The output is the following:
`[('MA0476.1', ['9606']), ('MA1951.1', ['9606'])]`

In this example, [**MA1951.1**](https://jaspar.genereg.net/matrix/MA1951.1/) should have species id **7719**.

**Comment by karolyp** [comment]
Investigating further, it seems that the MA19151.1 matrix belongs to TF Uncx-b and not the one that I queried for (FOS).

**Comment by asntech** [comment]
@karolyp thanks for reporting this. Your query is correct and also the output. We've some glitches on our web sever which will be fixed ASAP. Please check the development version here, it is a `FOS` not `Uncx-b`: https://jaspar.uio.no/matrix/MA1951.1/
